=== alex-fiennes/webmacro/contrib/ActionServlet/src/ActionServlet_0_5.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Action Servlet 0.5 DTD -->

<!ELEMENT application (templates?, type-handlers?, components)>

<!ELEMENT templates (template+)>
<!ELEMENT type-handlers (type-handler+)>
<!ELEMENT components (component+)>

<!ELEMENT template (output-variable*)>
<!ELEMENT type-handler EMPTY>
<!ELEMENT component (action*)>
<!ELEMENT action (output-variable*)>

<!ELEMENT output-variable EMPTY>

<!ATTLIST application
   repository CDATA #IMPLIED>

<!ATTLIST template
   name CDATA #REQUIRED
   is-new-session (true | false) "false">

<!ATTLIST type-handler
   type CDATA #REQUIRED
   class CDATA #REQUIRED>

<!ATTLIST component
   class CDATA #REQUIRED
   persistence (application | session | request) #REQUIRED>

<!ATTLIST action
   form CDATA #IMPLIED
   name CDATA #REQUIRED
   method CDATA #REQUIRED>

<!ATTLIST output-variable
   name CDATA #REQUIRED
   component CDATA #IMPLIED
   value CDATA #REQUIRED>

=== alex-fiennes/webmacro/contrib/ActionServlet/examples/Calculator/config/Calculator.xml
<?xml version="1.0"?>
<!DOCTYPE application SYSTEM "http://dione.zcu.cz/~toman40/ActionServlet/dtd/ActionServlet_0_5.dtd">

<application repository="c:/progra~1/ActionServlet/examples/Calculator/classes">
   <templates>
      <template name="Calculator.wm" is-new-session="true"/>
   </templates>

   <components>
      <component class="Calculator" persistence="session">
         <action name="0" method="digit(String action)"/>
         <action name="1" method="digit(String action)"/>
         <action name="2" method="digit(String action)"/>
         <action name="3" method="digit(String action)"/>
         <action name="4" method="digit(String action)"/>
         <action name="5" method="digit(String action)"/>
         <action name="6" method="digit(String action)"/>
         <action name="7" method="digit(String action)"/>
         <action name="8" method="digit(String action)"/>
         <action name="9" method="digit(String action)"/>

         <action name="." method="point()"/>
         <action name="+/-" method="plusminus()"/>

         <action name="+" method="operation(String action)"/>
         <action name="-" method="operation(String action)"/>
         <action name="*" method="operation(String action)"/>
         <action name="/" method="operation(String action)"/>
         <action name="=" method="operation(String action)"/>

         <action name="CE" method="ce()"/>
         <action name="C" method="c()"/>
      </component>
   </components>
</application>

=== alex-fiennes/webmacro/contrib/ActionServlet/examples/.orig/war/GuestBook.xml
<?xml version="1.0"?>
<!DOCTYPE application SYSTEM "http://dione.zcu.cz/~toman40/ActionServlet/dtd/ActionServlet_0_5.dtd">

<application>
   <templates>
      <template name="form.wm" is-new-session="true"/>
   </templates>

   <type-handlers>
      <type-handler type="Email" class="EmailHandler"/>
   </type-handlers>

   <components>
      <component class="GuestBook" persistence="application">
         <action name="form" method="showEmptyForm()"/>

         <action name="SUBMIT" 
                 method="verify(String name, Email email, String comment)"/>

         <action name="allguest" method="showAllGuests()"/>
      </component>
   </components>
</application>

=== alex-fiennes/webmacro/contrib/ActionServlet/examples/.orig/jsdk/OutputVars/config/OutputVars.xml
<?xml version="1.0"?>
<!DOCTYPE application SYSTEM "http://dione.zcu.cz/~toman40/ActionServlet/dtd/ActionServlet_0_5.dtd">

<application repository="@as.home@/examples/OutputVars/classes">
   <templates>
      <template name="template1.wm" is-new-session="true">
         <output-variable name="first" component="MyComponent" value="getFirst()"/>
         <output-variable name="lengthOfFirst" value="$first.length()"/>
      </template>

      <template name="template2.wm">
         <output-variable name="third" value="$second"/>
      </template>
   </templates>

   <components>
      <component class="MyComponent" persistence="application">
         <action name="Continue..." method="myAction()">
            <output-variable name="second" component="MyComponent" value="getSecond()"/>
            <output-variable name="lengthOfSecond" value="$second.length()"/>
         </action>
      </component>
   </components>
</application>

=== alex-fiennes/webmacro/contrib/ActionServlet/examples/.orig/jsdk/DateHandler/config/DateHandler.xml
<?xml version="1.0"?>
<!DOCTYPE application SYSTEM "http://dione.zcu.cz/~toman40/ActionServlet/dtd/ActionServlet_0_5.dtd">

<application repository="@as.home@/examples/DateHandler/classes">
   <templates>
      <template name="DateForm.wm" is-new-session="true"/>
   </templates>

   <type-handlers>
      <type-handler type="java.util.Date" class="DateHandler"/>
   </type-handlers>

   <components>
      <component class="DateComponent" persistence="application">
         <action name="Submit" method="submit(java.util.Date date)"/>
      </component>
   </components>
</application>
