=== alex-fiennes/webmacro/contrib/ActionServlet/src/ActionServlet_0_85.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Action Servlet 0.85 DTD -->

<!ELEMENT application (properties?, templates?, type-handlers?, components)>

<!ELEMENT properties (property+)>
<!ELEMENT templates (template+)>
<!ELEMENT type-handlers (type-handler+)>
<!ELEMENT components (component+)>

<!ELEMENT property EMPTY>
<!ELEMENT template (output-variable*)>
<!ELEMENT type-handler EMPTY>
<!ELEMENT component (action*, on-return*)>
<!ELEMENT action (output-variable*, on-return*)>
<!ELEMENT on-return (output-variable*)>

<!ELEMENT output-variable EMPTY>

<!ATTLIST application
   repository CDATA #IMPLIED>

<!ATTLIST property
   component CDATA #IMPLIED
   name CDATA #REQUIRED
   value CDATA #REQUIRED>

<!ATTLIST template
   name CDATA #REQUIRED
   is-new-session (true | false) "false">

<!ATTLIST type-handler
   type CDATA #REQUIRED
   class CDATA #REQUIRED>

<!ATTLIST component
   name CDATA #REQUIRED
   class CDATA #REQUIRED
   persistence (application | session | request | static) #REQUIRED>

<!ATTLIST action
   form CDATA #IMPLIED
   name CDATA #REQUIRED
   method CDATA #REQUIRED>

<!ATTLIST on-return
   value CDATA #REQUIRED
   assign-to CDATA #IMPLIED
   show-template CDATA #REQUIRED>

<!ATTLIST output-variable
   name CDATA #REQUIRED
   component CDATA #IMPLIED
   value CDATA #REQUIRED
   if CDATA #IMPLIED>

=== alex-fiennes/webmacro/contrib/ActionServlet/examples/Calculators/config/Calculators.xml
<?xml version="1.0"?>
<!DOCTYPE application SYSTEM "http://dione.zcu.cz/~toman40/ActionServlet/dtd/ActionServlet_0_85.dtd">

<application repository="C:/Progra~1/ActionServlet/examples/Calculators/classes">
   <templates>
      <template name="Calculators.wm" is-new-session="true">
         <output-variable name="display1" component="Calculator1" value="getDisplay()"/>
         <output-variable name="display2" component="Calculator2" value="getDisplay()"/>
      </template>
   </templates>

   <components>
      <component name="Calculator1" class="Calculator" persistence="session">
         <action form="1ST" name="0" method="digit(int action)"/>
         <action form="1ST" name="1" method="digit(int action)"/>
         <action form="1ST" name="2" method="digit(int action)"/>
         <action form="1ST" name="3" method="digit(int action)"/>
         <action form="1ST" name="4" method="digit(int action)"/>
         <action form="1ST" name="5" method="digit(int action)"/>
         <action form="1ST" name="6" method="digit(int action)"/>
         <action form="1ST" name="7" method="digit(int action)"/>
         <action form="1ST" name="8" method="digit(int action)"/>
         <action form="1ST" name="9" method="digit(int action)"/>

         <action form="1ST" name="." method="point()"/>
         <action form="1ST" name="+/-" method="plusminus()"/>

         <action form="1ST" name="+" method="operation(char action)"/>
         <action form="1ST" name="-" method="operation(char action)"/>
         <action form="1ST" name="*" method="operation(char action)"/>
         <action form="1ST" name="/" method="operation(char action)"/>
         <action form="1ST" name="=" method="operation(char action)"/>

         <action form="1ST" name="CE" method="ce()"/>
         <action form="1ST" name="C" method="c()"/>

         <on-return value="void" show-template="Calculators.wm"/>
      </component>

      <component name="Calculator2" class="Calculator2" persistence="session">
         <action form="2ND" name="0" method="digit(int action)"/>
         <action form="2ND" name="1" method="digit(int action)"/>
         <action form="2ND" name="2" method="digit(int action)"/>
         <action form="2ND" name="3" method="digit(int action)"/>
         <action form="2ND" name="4" method="digit(int action)"/>
         <action form="2ND" name="5" method="digit(int action)"/>
         <action form="2ND" name="6" method="digit(int action)"/>
         <action form="2ND" name="7" method="digit(int action)"/>
         <action form="2ND" name="8" method="digit(int action)"/>
         <action form="2ND" name="9" method="digit(int action)"/>

         <action form="2ND" name="." method="point()"/>
         <action form="2ND" name="+/-" method="plusminus()"/>

         <action form="2ND" name="+" method="operation(char action)"/>
         <action form="2ND" name="-" method="operation(char action)"/>
         <action form="2ND" name="*" method="operation(char action)"/>
         <action form="2ND" name="/" method="operation(char action)"/>
         <action form="2ND" name="=" method="operation(char action)"/>

         <action form="2ND" name="CE" method="ce()"/>
         <action form="2ND" name="C" method="c()"/>

         <action form="2ND" name="sin(x)" method="sin()"/>
         <action form="2ND" name="cos(x)" method="cos()"/>
         <action form="2ND" name="sqrt(x)" method="sqrt()"/>
         <action form="2ND" name="x^y" method="pow()"/>

         <on-return value="void" show-template="Calculators.wm"/>
      </component>
   </components>
</application>

=== alex-fiennes/webmacro/contrib/ActionServlet/examples/GuestBook/config/GuestBook.xml
<?xml version="1.0"?>
<!DOCTYPE application SYSTEM "http://dione.zcu.cz/~toman40/ActionServlet/dtd/ActionServlet_0_85.dtd">

<application>
   <templates>
      <template name="form.wm" is-new-session="true"/>

      <template name="allguest.wm">
         <output-variable name="registry" component="GuestBook" value="book"/>
      </template>
   </templates>

   <type-handlers>
      <type-handler type="Email" class="EmailHandler"/>
   </type-handlers>

   <components>
      <component name="GuestBook" class="GuestBook" persistence="application">
         <action name="show" method="show(String target)"/>
         <action name="SUBMIT" method="verify(Email email)">
            <on-return value="void" show-template="verify.wm"/>
         </action>
         <action name="PROCEED" method="proceed(String name, Email email, String comment)">
            <on-return value="void" show-template="allguest.wm"/>
         </action>
      </component>
   </components>
</application>
